spring:
   application:
      name: mdt.simulator
   servlet:
      multipart:
         maxFileSize: 200MB
         maxRequestSize: 200MB
      
server:
   port: 12987
   error:
      include-message: always

logging:
   level:
      root: INFO
   pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %-40.40logger{39} | %msg%n"

mdt-manager:
   endpoint: http://localhost:12985

skku:
   simulatorEndpoint: http://localhost:12987/skku
   simulationSubmodelRefString: 내함_성형/Simulation
   workingDirectory: C:\\Temp\\mdt\\simulator\\workspace
   command: [ "C:/Users/kwlee/AppData/Local/Programs/Microsoft VS Code/Code" ]
   timeout: PT5M
   sessionRetainTimeout: PT30S
 
operation-server:
   endpoint: http://localhost:12987
   operations: operations.json
   homeDir: ${MDT_HOME}/operation-server